repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v1.3.0
  hooks:
  - id: double-quote-string-fixer
  - id: flake8
    additional_dependencies: ["flake8-quotes==1.0.0", "flake8-mutable==1.2.0"]
- repo: https://github.com/pre-commit/mirrors-jshint
  rev: v2.9.6
  hooks:
  - id: jshint
