repos:
- repo: https://github.com/asottile/add-trailing-comma
  rev: v0.7.0
  hooks:
  - id: add-trailing-comma
    # TODO: Remove this line once we add trailing commas to all directories.
    files: ^api/|^tests
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v1.4.0
  hooks:
  - id: double-quote-string-fixer
  - id: trailing-whitespace
    exclude: website/static/vendor/*
  - id: flake8
    additional_dependencies: ["flake8==3.6.0", "flake8-mutable==1.2.0"]
- repo: https://github.com/pre-commit/mirrors-jshint
  rev: v2.9.6
  hooks:
  - id: jshint
