## Reference README-docker-compose.md for instructions.

services:

  #######
  # OSF #
  #######

  elasticsearch6:
    image: quay.io/centerforopenscience/elasticsearch/es6-arm-6.3.1
    platform: linux/arm64
