## Reference README-docker-compose.md for instructions.

services:

  #######
  # OSF #
  #######

  requirements:
    image: quay.io/centerforopenscience/osf:develop-arm64
    platform: linux/arm64

  assets:
    image: quay.io/centerforopenscience/osf:develop-arm64
    platform: linux/arm64
    # Need to allocate tty to be able to call invoke for requirements task
    tty: true

  admin_assets:
    image: quay.io/centerforopenscience/osf:develop-arm64
    platform: linux/arm64
    # Need to allocate tty to be able to call invoke for requirements task
    tty: true

  worker:
    image: quay.io/centerforopenscience/osf:develop-arm64
    platform: linux/arm64
    # Need to allocate tty to be able to call invoke for requirements task
    tty: true

  admin:
    image: quay.io/centerforopenscience/osf:develop-arm64
    platform: linux/arm64
    # Need to allocate tty to be able to call invoke for requirements task
    tty: true

  api:
    image: quay.io/centerforopenscience/osf:develop-arm64
    platform: linux/arm64
    # Need to allocate tty to be able to call invoke for requirements task
    tty: true

  web:
    image: quay.io/centerforopenscience/osf:develop-arm64
    platform: linux/arm64
    # Need to allocate tty to be able to call invoke for requirements task
    tty: true

